### ISSUE TITLE
breaks whisper app

### ISSUE THREAD

**Issue by themotu** [ZonD80/duppy#10]
installing crackerxi+ and trying to use duppy breaks the whisper app completely

**Comment by ZonD80** [comment]
App itself (or it's duplicate) or duppy crashes?

**Comment by themotu** [comment]
The app itself. Can’t be re-opened until crackerxi is uninstalled

**Comment by ZonD80** [comment]
I have nothing to do with such interference, as I'm not developer of Signal or CrackerXI
