### ISSUE TITLE
Duplicated YouTube app can’t log in/load anything

### ISSUE THREAD

**Issue by incIined** [ZonD80/duppy#11]
Gives me an “error loading, tap to retry”. Trying to switch accounts gives me an “error fetching channel list”. Trying to clone YT 15.35.2. 

Is this something Duppy can fix, or is it Google’s issue that Duppy can do nothing about? Thanks.

**Comment by ZonD80** [comment]
It's issue of bundle identifier format, it must start with com.google.youtube I suppose, duppy uses another format duppy.*

**Comment by ZonD80** [comment]
Please try again with 1.2.1

**Comment by ZonD80** [comment]
Closing as there is no response from submitter

**Comment by incIined** [comment]
Sorry for the late response, but I just updated the app and can confirm it duplicates YouTube perfectly now. Thanks! 

(Also a bit off-topic, but how do you see the current app version from within the app?)
