### ISSUE TITLE
cloned app crashed instantly

### ISSUE THREAD

**Issue by wtoib** [ZonD80/duppy#9]
I used duppy v1.4 to clone the "LINE" social app, but the cloned app crashed instantly when I ran it. Could you help solve the issue of the cloned **LINE** app? Thank you.
My device is iphone xs with ios 13.5 and unc0ver jb.
In addition, duppy v1.4 above itself will crash as well.

**Comment by wtoib** [comment]
![E29A0658-4268-4409-8325-D7104C7AD0F6](https://user-images.githubusercontent.com/67180825/85193484-8bc99200-b2fb-11ea-9358-0a40188fe390.png)

**Comment by ZonD80** [comment]
replied on reddit
